server:
  port: 8080


spring:
  cloud:
    gateway:
      routes:
        - id: word-generator
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/word-generator/**
          filters:
            - StripPrefix=2
        - id: word-processor
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/word-processor/**
          filters:
            - StripPrefix=2
        - id: notification-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/notifications/**
          filters:
            - StripPrefix=2
        - id: notification-websocket
          uri: ws://localhost:8083
          predicates:
            - Path=/api/v1/notifications/ws/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE

management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    io:
      netty:
        handler:
          codec:
            http: DEBUG